### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/dragonfly_speech_recognition#16]
```
[ERROR] [1495292813.091909]: _determine_answer raised an exception: Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/abstract_server.py", line 33, in _execute_cb
    is_preempt_requested=self._is_preempt_requested)
  File "/home/amigo/ros/kinetic/system/src/dragonfly_speech_recognition/src/dragonfly_speech_recognition/hmi_server_dragonfly_client.py", line 19, in _determine_answer
    result = c.recognize(grammar, target, is_preempt_requested)
  File "/home/amigo/ros/kinetic/system/src/dragonfly_speech_recognition/src/dragonfly_speech_recognition/dragonfly_client.py", line 35, in recognize
    sentence = conn.recv()
EOFError
```

**Comment by Rayman** [comment]
I don't think its related, but this was the error on the windows side:

![screenshot from 2017-05-20 17-21-34](https://cloud.githubusercontent.com/assets/91969/26277078/0f867ddc-3d85-11e7-9d27-5b9637b9b792.png)

**Comment by MatthijsBurgh** [comment]
@Rayman still an issue?

**Comment by Rayman** [comment]
The speach bug that we had during rwc2017 was different. I'll close this one for now.
