### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/dragonfly_speech_recognition#33]
https://gist.github.com/rdapaz/63590adb94a46039ca4a10994dff9dbe

**Comment by MatthijsBurgh** [comment]
```cmd
C:\WINDOWS\system32>python -u "C:\Users\amigo\dragonfly_speech_recognition\scripts\dragonfly_server" --ip 192.168.44.53
2022-03-01 20:58:14,953 dragonfly_server [INFO] Setting up DragonflyServer 192.168.44.53:3000
Traceback (most recent call last):
  File "C:\Users\amigo\dragonfly_speech_recognition\scripts\dragonfly_server", line 17, in <module>
    c = DragonflyServer(args.ip, args.port)
  File "C:\Users\amigo\dragonfly_speech_recognition\scripts/../src\dragonfly_speech_recognition\dragonfly_server.py", line 34, in __init__
    self._dragonfly_wrapper = DragonflyWrapper()
  File "C:\Users\amigo\dragonfly_speech_recognition\scripts/../src\dragonfly_speech_recognition\dragonfly_wrapper.py", line 26, in __init__
    self._engine = Sapi5InProcEngine()
  File "c:\users\amigo\dragonfly_speech_recognition\src\dragonfly_speech_recognition\dragonfly\dragonfly\engines\backend_sapi5\engine.py", line 111, in __init__
    EnsureDispatch(self.recognizer_dispatch_name)
  File "C:\Python310\lib\site-packages\win32com\client\gencache.py", line 618, in EnsureDispatch
    disp = win32com.client.Dispatch(prog_id)
  File "C:\Python310\lib\site-packages\win32com\client\__init__.py", line 118, in Dispatch
    return __WrapDispatch(dispatch, userName, resultCLSID, typeinfo, clsctx=clsctx)
  File "C:\Python310\lib\site-packages\win32com\client\__init__.py", line 46, in __WrapDispatch
    klass = gencache.GetClassForCLSID(resultCLSID)
  File "C:\Python310\lib\site-packages\win32com\client\gencache.py", line 197, in GetClassForCLSID
    mod = GetModuleForCLSID(clsid)
  File "C:\Python310\lib\site-packages\win32com\client\gencache.py", line 242, in GetModuleForCLSID
    mod = GetModuleForTypelib(typelibCLSID, lcid, major, minor)
  File "C:\Python310\lib\site-packages\win32com\client\gencache.py", line 284, in GetModuleForTypelib
    AddModuleToCache(typelibCLSID, lcid, major, minor)
  File "C:\Python310\lib\site-packages\win32com\client\gencache.py", line 658, in AddModuleToCache
    SetTypelibForAllClsids(mod.CLSIDToClassMap)
AttributeError: module 'win32com.gen_py.C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4' has no attribute 'CLSIDToClassMap'
```

**Comment by MatthijsBurgh** [comment]
Fixed by https://github.com/tue-robotics/dragonfly_speech_recognition/pull/35
